services:
  mongodb:
    image: mongo:latest
    container_name: leaderboard-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: leaderboard-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: leaderboard-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Giữ node_modules ổn định trong container
    depends_on:
      - mongodb
      - redis
    restart: always

volumes:
  mongo_data:
  redis_data:
